version: "3"

services:
   backend:
      build: ./php
   frontend:
      build: ./public_html
      image: nginx:latest
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./production.conf:/etc/nginx/conf.d/default.conf
         - ./public_html:/usr/share/nginx/html
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/rainbowsnow.best/fullchain.pem:/etc/letsencrypt/live/rainbowsnow.best/fullchain.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/rainbowsnow.best/privkey.pem:/etc/letsencrypt/live/rainbowsnow.best/privkey.pem